{% set version = "0.3.0" %}
{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
{% set processor = "cpu" %}  # [not linux64]

package:
  name: hoomd-dlext
  version: {{ version }}

source:
  url: https://github.com/SSAGESLabs/hoomd-dlext/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 438c032befdc8115fb40c71bebb025bb2936382ac26f0df650b4acb5d8c07d0a

build:
  number: 1
  # Upstream package does not support Windows, Python < 3.6, or PyPy
  skip: true  # [win or py<36 or python_impl == "pypy"]
  skip: true  # [hoomd == "v3" and cuda_compiler_version not in ("11.2", "None")]
  string: hoomd{{ hoomd }}_{{ processor }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  ignore_run_exports_from:
    - tbb-devel

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cmake >=3.16,!=3.23.0
    - make

  host:
    - python
    - pybind11
    - dlpack >=0.5
    - eigen         # [hoomd == "v3"]
    - hoomd <3      # [hoomd == "v2"]
    - hoomd >=3.5   # [hoomd == "v3"]
    - tbb-devel

  run:
    - python
    - {{ pin_compatible('hoomd', max_pin='x.x') }}

test:
  imports:
    - hoomd.dlext

about:
  home: https://github.com/SSAGESLabs/hoomd-dlext
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Wrapper for HOOMD-blue simulation data into DLPack data structures.

  description: |
    Provides access to HOOMD-blue simulation data on CPU or GPU via DLPack.
    This project is primarily designed to enable access to HOOMD-blue for
    the PySAGES project. At the moment, only HOOMD-blue version 2 is supported
    (support HOOMD-blue version 3 is in the works).

  doc_url: https://github.com/SSAGESLabs/hoomd-dlext
  dev_url: https://github.com/SSAGESLabs/hoomd-dlext

extra:
  recipe-maintainers:
    - pabloferz
    - nrouizem
